daily

diff --git a/pybrat-install b/pybrat-install
--- a/pybrat-install
+++ b/pybrat-install
@@ -38,21 +38,42 @@ function _search_path {
 
 
 
+function _config_shrc_pybrew {
+
+    echo; read -p "Configure 'pythonbrew' in your '~/.bashrc'? [y/N]: "
+    if [[ "$REPLY" != "y" ]]; then
+	printf "\n==> ERROR: 'pythonbrew' needs to be configured to work!\n"
+	_err; return
+    fi
+
+    printf "\n# 'pythonbrew' environment configuration\n" >> ${HOME}/.bashrc
+    echo "[[ -s ${HOME}/.pythonbrew/etc/bashrc ]] && source ${HOME}/.pythonbrew/etc/bashrc" \
+	>> ${HOME}/.bashrc
+
+    echo; echo '==> DONE! You need to restart your shell. Type `exec $SHELL`.'
+    printf "\n(On uninstall, delete 'pythonbrew' section from '${HOME}/.bashrc'.)\n"
+
+    return
+}
+
+
+
 # Check if 'pythonbrew' installed and if not, install.
 function _check_req_pybrew {
 
     _search_path "${DEF_PYBREW}/bin"
     [ ! $FIND_PATH ] && return
 
-    if [[ -d "$DEF_PYBREW" ]]; then
+    if [ -e "$DEF_PYBREW" ]; then
 	echo "==> WARNING: 'pythonbrew' installed but not configured."
 	echo "Did you configure your shell script and type `exec $SHELL`?"
+        _config_shrc_pybrew
 	_err; return
     fi
 
     # good to install ...
-    echo "This (development) version still requires (deprecated) 'pythonbrew'."
-    read -p "Download and install 'pythonbrew' to defaults using 'curl'? [y/N]: "
+    echo "==> ERROR: This (development) version still requires (deprecated) 'pythonbrew'."
+    read -p "Use 'curl' to install 'pythonbrew' to defaults? [y/N]: "
     [[ "$REPLY" != "y" ]] && _err && return
 
     # ... so curl it all to defaults
@@ -63,63 +84,18 @@ function _check_req_pybrew {
 	_err; return
     fi
 
-    echo; read -p "Configure 'pythonbrew' in your '~/.bashrc'? [y/N]: "
-    if [[ "$REPLY" != "y" ]]; then
-	printf "\n*** 'pythonbrew' needs to be configured to work! ***\n"
-	_err; return
-    fi
-
-    printf "\n# 'pythonbrew' environment configuration\n" >> ${HOME}/.bashrc
-    echo "[[ -s ${HOME}/.pythonbrew/etc/bashrc ]] && source ${HOME}/.pythonbrew/etc/bashrc" \
-	>> ${HOME}/.bashrc
-
-    echo; echo 'DONE! You need to restart your shell. Type `exec $SHELL`.'
-    printf "\n(On uninstall, delete 'pythonbrew' section from '${HOME}/.bashrc'.)\n"
-
+    _config_shrc_pybrew
     _err; return
 }
 
 
 
-# Check if 'pyenv' and plugins are installed and if not, install.
-function _check_req_pyenv {
+# Configure the user's shell script if they want.
+function _config_shrc_pyenv {
 
-    _search_path "${DEF_PYENV}/bin"
-#############
-    echo "$FIND_PATH"
-    [ ! -z "$FIND_PATH" ] && return
-
-    # check for .pyenv directory in case installed but not config'd
-    if [[ ! -d "$DEF_PYENV" ]]; then
-        echo "==> WARNING: 'pyenv' installed but not configured."
-        echo "Did you read the 'README.md' in '${DEF_PYENV}'?"
-	_err; return
-    fi
-
-    # good to install here ...
-    echo "This version of PyBrat requires 'pyenv'."
-    read -p "Download and install 'pyenv' to defaults from 'github'? [y/N]: "
-    [[ "$REPLY" != "y" ]] && _err && return
-    
-    # ... so clone it all from github
-    echo
-    git clone git://github.com/yyuu/pyenv.git $DEF_PYENV
-    if [ ! -e "${DEF_PYENV}" ]; then
-        echo "==> ERROR: 'pyenv' did not install correctly."
-	_err; return
-    fi
-
-    echo
-    git clone git://github.com/yyuu/pyenv-virtualenv.git ${DEF_PYENV}/plugins/pyenv-virtualenv
-    if [ ! -e "${DEF_PYENV}/plugins/pyenv-virtualenv" ]; then
-        echo "==> ERROR: 'pyenv-virtualenv' did not install correctly."
-	_err; return
-    fi
-
-    # auto-configure for bash if user wants
     echo; read -p "Configure 'pyenv' for your shell? [y/N]: "
     if [[ "$REPLY" != "y" ]]; then
-        printf "\n*** 'pyenv' needs to be configured to work! ***\n"
+        printf "\n==> ERROR: 'pyenv' needs to be configured to work!\n"
         echo "Read the 'README.md' located in the '${DEF_PYENV}' directory."
 	_err; return
     fi
@@ -144,9 +120,48 @@ function _check_req_pyenv {
     echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ${HOME}/${sh}
     echo 'eval "$(pyenv init -)"' >> ${HOME}/${sh}
     
-    echo; echo 'DONE! You need to restart your shell. Type `exec $SHELL`.'
+    echo; echo '==> DONE! You need to restart your shell. Type `exec $SHELL`.'
     printf "\n(On uninstall, delete 'pyenv' section from '${HOME}/${sh}'.)\n"
 
+    return
+}
+
+
+
+# Check if 'pyenv' and plugins are installed and if not, install.
+function _check_req_pyenv {
+
+    _search_path "${DEF_PYENV}/bin"
+    [ ! $FIND_PATH ] && return
+
+    # check for .pyenv directory in case installed but not config'd
+    if [ -e "$DEF_PYENV" ]; then
+        echo "==> ERROR: 'pyenv' installed but not configured."
+        echo "Did you read the 'README.md' in '${DEF_PYENV}'?"
+        _config_shrc_pyenv
+	_err; return
+    fi
+
+    # good to install here ...
+    echo "==> ERROR: This version of PyBrat requires 'pyenv'."
+    read -p "Use 'git' to clone and install 'pyenv' to defaults? [y/N]: "
+    [[ "$REPLY" != "y" ]] && _err && return
+    
+    # ... so clone it all from github
+    echo
+    git clone git://github.com/yyuu/pyenv.git $DEF_PYENV
+    if [ ! -e "$DEF_PYENV" ]; then
+        echo "==> ERROR: 'pyenv' did not install correctly."
+	_err; return
+    fi
+    echo
+    git clone git://github.com/yyuu/pyenv-virtualenv.git ${DEF_PYENV}/plugins/pyenv-virtualenv
+    if [ ! -e "${DEF_PYENV}/plugins/pyenv-virtualenv" ]; then
+        echo "==> ERROR: 'pyenv-virtualenv' did not install correctly."
+	_err; return
+    fi
+
+    _config_shrc_pyenv
     _err; return
 }
 
@@ -168,30 +183,50 @@ function _check_req_pyver {
 
 
 
+function _check_req {
+    _check_req_pyenv
+    _check_req_pyver
+    _check_req_pybrew     # to be deprecated
+}
+
+
+# make sure the python installer exists first, then run it
+function _run_pyinstall {
+    if [ -e "${PWD}/scripts/pybrat_install.py" ]; then 
+        /usr/bin/python2 "${PWD}/scripts/pybrat_install.py" $@
+    else
+        echo "Install module not found."
+    fi
+}
+
+
+
 #===========================================#
 #                    MAIN                   #
 #===========================================#
 
-ARGS=
+OPTIND=1
 
-[[ "$#" == "0" ]] && ARGS="-i" || ARGS="$@"
+while getopts "hi" opt; do
+    case "$opt" in
+        h)
+            _run_pyinstall -h; exit 1
+            ;;
+        i)
+            _search_path $PYBRAT_HOME
+            [ ! $FIND_PATH ] && echo "PyBrat is already installed. Uninstall first." && exit 1
+            ;;
+    esac
+done
 
-echo "$ARGS"
+# pre-parse the args before sending to python installer
+[[ "$#" == "0" ]] && ARG="-i" || ARG="$1"
 
-_check_req_pyenv
-_check_req_pyver
-_check_req_pybrew
+# clear to check for dependencies before installing
+_check_req
 [ ! -z "$ERR" ] && echo "==> ERROR (${ERR}): Try reinstalling after fixing stuff." && exit $ERR
 
-if [[ "$1" == "-i" || "$1" == "--install" ]]; then
-    _search_path $PYBRAT_HOME
-    [ ! $FIND_PATH ] && echo "PyBrat is already installed. Uninstall first." && exit 1
-fi
-
-if [[ -e "${PWD}/scripts/pybrat_install.py" ]]; then 
-    /usr/bin/python2 "${PWD}/scripts/pybrat_install.py" $ARGS
-else
-    echo "Install module not found."
-fi
+# otherwise, send the args on to python installer ...
+_run_pyinstall $ARG
 
 exit
